import { getBlogPostBySlug, getBlogPosts, getCaseStudies, getCaseStudyBySlug, getClientLogos, getFaqs, getJobs, getJobBySlug, getServices, getTestimonials } from '../services/contentApi.js';
import { mediaUrl } from '../services/cmsApi.js';
import { esc } from '../utils/content.js';

const safe = v => esc(v || '');
const image = item => item ? mediaUrl(item) : '';

export async function renderCaseStudiesPage() {
  const [items, logos] = await Promise.all([getCaseStudies({ 'filters[featured][$eq]': true }), getClientLogos()]);
  return `<main><section class="page-title"><div class="container"><p class="eyebrow">Proof</p><h1>Case studies & delivery stories.</h1><p class="page-intro">Explore selected examples of operational and technology work. Client identities are shown only where approved.</p></div></section>${renderLogoStrip(logos)}<section class="content-list-section"><div class="container"><div class="card-grid">${items.map(renderCaseCard).join('') || empty('Case studies will appear here as approved stories are published.')}</div></div></section></main>`;
}
export async function renderCaseStudyDetail(slug) { const item=await getCaseStudyBySlug(slug); if(!item)return null; return `<main><section class="page-title"><div class="container"><p class="eyebrow">Case study</p><h1>${safe(item.title)}</h1><p class="page-intro">${safe(item.summary)}</p></div></section><article class="article"><div class="container narrow">${item.featuredImage ? `<img class="article-image" src="${safe(image(item.featuredImage))}" alt="${safe(item.featuredImage.alternativeText)}">` : ''}${articleBlock('Challenge',item.challenge)}${articleBlock('Solution',item.solution)}${articleBlock('Implementation',item.implementation)}${articleBlock('Results',item.results)}${item.metrics?.length ? `<section><h2>Selected metrics</h2><div class="metric-grid">${item.metrics.map(m=>`<div><strong>${safe(m.value)}</strong><span>${safe(m.label)}</span></div>`).join('')}</div></section>`:''}${item.technologies?.length ? `<section><h2>Technology</h2><p>${item.technologies.map(t=>safe(typeof t==='string'?t:t.name)).join(' · ')}</p></section>`:''}</div></article></main>`; }
export async function renderBlogPage() { const items=await getBlogPosts({ 'filters[featured][$eq]': true }); return `<main><section class="page-title"><div class="container"><p class="eyebrow">Insights</p><h1>Ideas from operations, technology and delivery.</h1></div></section><section class="content-list-section"><div class="container"><div class="card-grid">${items.map(renderPostCard).join('') || empty('Insights will appear here as posts are published.')}</div></div></section></main>`; }
export async function renderBlogDetail(slug) { const item=await getBlogPostBySlug(slug); if(!item)return null; return `<main><article class="article"><div class="container narrow"><p class="eyebrow">Insight</p><h1>${safe(item.title)}</h1><p class="article-meta">${safe(item.publishedDate)}${item.readingTime?` · ${safe(item.readingTime)} min read`:''}</p>${item.featuredImage?`<img class="article-image" src="${safe(image(item.featuredImage))}" alt="${safe(item.featuredImage.alternativeText)}">`:''}<p class="article-lead">${safe(item.excerpt)}</p><div class="rich-copy">${item.content || ''}</div></div></article></main>`; }
export async function renderCareersPage() { const jobs=await getJobs(); return `<main><section class="page-title"><div class="container"><p class="eyebrow">Careers</p><h1>Build dependable work with AHAD.</h1><p class="page-intro">Explore current opportunities and find where your skills can contribute.</p></div></section><section class="content-list-section"><div class="container"><div class="job-list">${jobs.map(j=>`<a class="job-card" href="/careers/${safe(j.slug)}"><div><p class="eyebrow">${safe(j.department)}</p><h2>${safe(j.title)}</h2><p>${safe(j.summary)}</p></div><span>View role ↗</span></a>`).join('') || empty('No open positions are currently published.')}</div></div></section></main>`; }
export async function renderJobDetail(slug) { const job=await getJobBySlug(slug); if(!job)return null; const { renderCareerForm }=await import('../components/forms/CareerForm.js'); return `<main><section class="page-title"><div class="container"><p class="eyebrow">${safe(job.department)} · ${safe(job.workMode)}</p><h1>${safe(job.title)}</h1><p class="page-intro">${safe(job.summary)}</p></div></section><section class="article"><div class="container two-column"><div class="rich-copy">${articleBlock('Role',job.description)}${articleBlock('Responsibilities',job.responsibilities)}${articleBlock('Requirements',job.requirements)}${articleBlock('Benefits',job.benefits)}</div><div><div class="form-card"><p class="eyebrow">Apply</p><h2>Interested in this role?</h2>${renderCareerForm(job)}</div></div></div></section></main>`; }
export function renderTestimonials(items=[]) { return `<section class="testimonials-section"><div class="container"><p class="eyebrow">Testimonials</p><h2>What clients say about the work.</h2><div class="testimonial-grid">${items.map(t=>`<figure><blockquote>“${safe(t.quote)}”</blockquote><figcaption><strong>${safe(t.personName)}</strong><span>${safe(t.designation)}${t.company?` · ${safe(t.company)}`:''}</span></figcaption></figure>`).join('') || empty('Approved testimonials will appear here.')}</div></div></section>`; }
export async function renderFAQPage(){ const items=await getFaqs(); return `<main><section class="page-title"><div class="container"><p class="eyebrow">Questions</p><h1>Frequently asked questions.</h1></div></section><section class="faq-section"><div class="container narrow"><div class="faq-list">${items.map(f=>`<details><summary>${safe(f.question)}<span>+</span></summary><p>${safe(f.answer)}</p></details>`).join('') || empty('FAQs will appear here as they are approved.')}</div></div></section></main>`; }
function renderCaseCard(item){return `<a class="content-card" href="/case-studies/${safe(item.slug)}">${item.featuredImage?`<img src="${safe(image(item.featuredImage))}" alt="${safe(item.featuredImage.alternativeText)}">`:''}<div><p class="eyebrow">Case study</p><h2>${safe(item.title)}</h2><p>${safe(item.summary)}</p><span class="text-link">Read story →</span></div></a>`;}
function renderPostCard(item){return `<a class="content-card" href="/blog/${safe(item.slug)}">${item.featuredImage?`<img src="${safe(image(item.featuredImage))}" alt="${safe(item.featuredImage.alternativeText)}">`:''}<div><p class="eyebrow">Insight</p><h2>${safe(item.title)}</h2><p>${safe(item.excerpt)}</p><span class="text-link">Read insight →</span></div></a>`;}
function renderLogoStrip(logos){if(!logos?.length)return '';return `<section class="logo-strip"><div class="container"><p class="eyebrow">Selected client logos</p><div>${logos.map(l=>l.logo?`<img src="${safe(image(l.logo))}" alt="${safe(l.name)}" loading="lazy">`:`<span>${safe(l.name)}</span>`).join('')}</div></div></section>`;}
function articleBlock(title,content){return content?`<section><h2>${safe(title)}</h2><div class="rich-copy">${typeof content==='string'?content:safe(content)}</div></section>`:'';}
function empty(message){return `<div class="empty-state"><h2>Nothing published yet</h2><p>${safe(message)}</p></div>`;}
